<script setup lang="ts">
import { computed, onMounted, ref, watch, watchEffect } from 'vue'; import { useRoute, useRouter } from 'vue-router'
import PageTitle from '../components/common/PageTitle.vue'; import SourceBadge from '../components/common/SourceBadge.vue'; import { useSystemData } from '../composables/useSystemData'; import { api } from '../services/api'
const route=useRoute(),router=useRouter(); const {devices,alarms,error,refresh}=useSystemData(); const selected=ref(''); const tab=ref(route.query.tab==='alarms'?'alarms':'telemetry'); const windowHours=ref(1); const history=ref<Record<string,Array<{ts:number;value:string|number|boolean}>>>({});
const device=computed(()=>devices.value.find(d=>d.id===selected.value)??devices.value[0]); const chartValues=computed(()=>Object.values(history.value)[0]??[])
watchEffect(()=>{if(!selected.value&&devices.value.length)selected.value=devices.value[0].id})
async function loadHistory(){history.value={};if(device.value.source==='live'){const end=Date.now();history.value=await api.nodeHistory(device.value.id,end-windowHours.value*3600000,end).catch(()=>({}))}}
function setTab(value:string){tab.value=value;router.replace({query:value==='alarms'?{tab:'alarms'}:{}})} async function act(id:string|undefined,type:'ack'|'clear'){if(!id)return;type==='ack'?await api.acknowledgeAlarm(id):await api.clearAlarm(id);await refresh()}
watch([selected,windowHours],loadHistory); onMounted(loadHistory)
</script>
<template><div class="view-stack"><PageTitle eyebrow="Telemetry & cloud evidence" title="Monitor" description="Live telemetry, historical trends, alarms and device events."/><section class="raised-card monitor-toolbar"><label>Device<select v-model="selected"><option v-for="d in devices" :key="d.id" :value="d.id">{{d.displayName}}</option></select></label><SourceBadge :source="device.source"/><span>Updated: {{device.lastUpdate?new Date(device.lastUpdate).toLocaleString():'Simulation baseline'}}</span><div class="time-window"><button v-for="h in [1,6,24,168]" :key="h" :class="{active:windowHours===h}" @click="windowHours=h">{{h===168?'7d':`${h}h`}}</button></div></section><div class="tab-row"><button :class="{active:tab==='telemetry'}" @click="setTab('telemetry')">Telemetry</button><button :class="{active:tab==='alarms'}" @click="setTab('alarms')">Alarms & Events</button></div>
<template v-if="tab==='telemetry'"><section class="metric-grid"><article v-for="(value,key) in device.telemetry" :key="key" class="raised-card metric-card"><small>{{String(key).replaceAll('_',' ')}}</small><strong>{{typeof value==='boolean'?(value?'YES':'NO'):value}}</strong></article></section><section class="raised-card telemetry-chart"><div class="card-heading"><div><h2>Historical telemetry</h2></div><span>ThingsBoard · {{windowHours===168?'7d':`${windowHours}h`}}</span></div><svg v-if="chartValues.length>1" viewBox="0 0 600 150" preserveAspectRatio="none"><polyline :points="chartValues.map((p,i)=>`${i*600/(chartValues.length-1)},${140-(Number(p.value)||0)}`).join(' ')"/></svg><div v-else class="empty-inline">{{device.source==='live'?'No samples returned for this window.':'Historical simulation is intentionally not fabricated.'}}</div></section></template>
<template v-else><p v-if="error" class="notice warning">{{error}}</p><section class="raised-card table-card"><div v-if="!alarms.length" class="empty-state"><b>No alarm records returned</b><span>No simulated alarms or events are fabricated.</span></div><template v-else><div class="alarm-row header"><span>Type</span><span>Severity</span><span>Time</span><span>Status</span><span>Actions</span></div><div v-for="a in alarms" :key="a.id?.id" class="alarm-row"><b>{{a.type}}</b><span>{{a.severity}}</span><span>{{new Date(a.createdTime??a.startTs??0).toLocaleString()}}</span><span>{{a.status}}</span><span><button v-if="!a.acknowledged" class="text-button" @click="act(a.id?.id,'ack')">Acknowledge</button><button v-if="!a.cleared" class="text-button coral" @click="act(a.id?.id,'clear')">Clear</button></span></div></template></section><section class="raised-card event-note"><h2>System events</h2><p>Event persistence is not configured. No production events are fabricated.</p></section></template></div></template>
