<script setup lang="ts">
import { Check, Copy, KeyRound, Plus, X } from '@lucide/vue'
import { reactive, ref } from 'vue'
import PageTitle from '../components/common/PageTitle.vue'; import SourceBadge from '../components/common/SourceBadge.vue'
import { useSystemData } from '../composables/useSystemData'; import { api } from '../services/api'
import type { DeviceCreatePayload, DeviceProvisionResponse, DeviceViewModel } from '../types/device'
const { devices } = useSystemData(); const selected = ref<DeviceViewModel|null>(null); const showForm=ref(false), saving=ref(false), message=ref(''), copied=ref(false); const provisioned=ref<DeviceProvisionResponse|null>(null)
const form=reactive<DeviceCreatePayload>({display_name:'',device_name:'',zone:'',purpose:'',telemetry_contract:[],rpc_methods:[],notes:''}); const telemetryText=ref(''),rpcText=ref('')
async function submit(){saving.value=true;message.value='';try{form.telemetry_contract=telemetryText.value.split(',').map(v=>v.trim()).filter(Boolean);form.rpc_methods=rpcText.value.split(',').map(v=>v.trim()).filter(Boolean);provisioned.value=await api.createDevice(form)}catch(e){message.value=e instanceof Error?e.message:'Node creation failed'}finally{saving.value=false}}
async function copyConfig(){if(provisioned.value){await navigator.clipboard.writeText(provisioned.value.edge_config_template);copied.value=true}}
</script>
<template><div class="view-stack"><PageTitle eyebrow="Inventory & onboarding" title="Project Nodes" description="Device identity, contracts, connectivity and safe ThingsBoard provisioning in one place."><button class="action-button" @click="showForm=true"><Plus/> Add Node</button></PageTitle>
<section class="raised-card table-card"><div class="device-table header"><span>Node</span><span>Zone / Purpose</span><span>Source</span><span>Connectivity</span><span>Actions</span></div><div v-for="d in devices" :key="d.id" class="device-table"><span><b>{{d.displayName}}</b><small>{{d.id}}</small></span><span>{{d.zone}}<small>{{d.purpose}}</small></span><SourceBadge :source="d.source"/><span class="connectivity"><i :class="d.online?'ok':'muted'"/>{{d.online?'Online':'Not connected'}}</span><button class="text-button" @click="selected=d">View details</button></div></section>
<section v-if="selected" class="raised-card node-detail"><div class="card-heading"><div><KeyRound/><h2>{{selected.displayName}}</h2></div><button class="text-button" @click="selected=null">Close</button></div><div class="detail-grid"><dl><div><dt>Stable name</dt><dd>{{selected.id}}</dd></div><div><dt>Zone</dt><dd>{{selected.zone}}</dd></div><div><dt>Source</dt><dd>{{selected.source.toUpperCase()}}</dd></div><div><dt>Last telemetry</dt><dd>{{selected.lastUpdate?new Date(selected.lastUpdate).toLocaleString():'No live sample'}}</dd></div></dl><div><h3>Telemetry contract</h3><p>{{Object.keys(selected.telemetry).join(', ')}}</p></div></div></section>
<div v-if="showForm" class="modal-backdrop"><section class="modal raised-card"><button class="modal-close" @click="showForm=false"><X/></button><p class="eyebrow">ThingsBoard provisioning</p><h2>Add Node</h2><form class="form-grid" @submit.prevent="submit"><label>Display name<input v-model="form.display_name" required/></label><label>Stable device name<input v-model="form.device_name" required placeholder="node-2-exit-monitoring"/></label><label>Zone<input v-model="form.zone" required/></label><label>Purpose<input v-model="form.purpose" required/></label><label class="wide">Telemetry fields<input v-model="telemetryText"/></label><label class="wide">RPC methods<input v-model="rpcText"/></label><label class="wide">Notes<textarea v-model="form.notes"/></label><p v-if="message" class="notice warning wide">{{message}}</p><button class="action-button wide" :disabled="saving">{{saving?'Creating…':'Create in ThingsBoard'}}</button></form><div v-if="provisioned" class="provision-result"><p><Check/> Created <b>{{provisioned.device_name}}</b></p><pre>{{provisioned.edge_config_template}}</pre><button class="soft-button" @click="copyConfig"><Copy/> {{copied?'Copied':'Copy Edge Config'}}</button><small>{{provisioned.credential_message}}</small></div></section></div></div></template>
